alias getupdates="sudo apt-get update && sudo apt-get upgrade"
alias mountandroid="go-mtpfs /media/MyAndroid"
alias unmountandroid="fusermount -u /media/MyAndroid"
alias :q="exit"
alias list="ls -lisaF"
